"""
crosswalks_pipeline.py
──────────────────────────────────────────────────────────────────────
Data pipeline: Italian pedestrian crosswalk density analysis.

Input:  notebooks/raw/crosswalks_raw.csv
Output: data/crosswalks-italy.json

Run from project root:
    python notebooks/crosswalks_pipeline.py

Requires: pandas (pip install pandas)
──────────────────────────────────────────────────────────────────────
"""

import json
import csv
from pathlib import Path
from datetime import date

# ── Paths ────────────────────────────────────────────────────────────
ROOT = Path(__file__).parent.parent
RAW = ROOT / "notebooks" / "raw" / "crosswalks_raw.csv"
OUT = ROOT / "data" / "crosswalks-italy.json"


# ── Load raw data ─────────────────────────────────────────────────────
def load_raw(path: Path) -> list[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


# ── Compute score ─────────────────────────────────────────────────────
def compute_score(population: int, crosswalks: int) -> float:
    """Crossings per 10 000 inhabitants, rounded to 1 decimal."""
    if population == 0:
        return 0.0
    return round((crosswalks / population) * 10_000, 1)


# ── Process ───────────────────────────────────────────────────────────
def process(rows: list[dict]) -> dict:
    cities = []
    for row in rows:
        pop = int(row["population_2023"])
        cwk = int(row["osm_crosswalk_count"])
        score = compute_score(pop, cwk)
        cities.append(
            {
                "name": row["city"],
                "region": row["region"],
                "province_code": row["province_code"],
                "population": pop,
                "crosswalks": cwk,
                "score": score,
            }
        )

    # Sort by score descending
    cities.sort(key=lambda c: c["score"], reverse=True)

    scores = [c["score"] for c in cities]
    total_crosswalks = sum(c["crosswalks"] for c in cities)
    national_avg = round(sum(scores) / len(scores), 1)

    return {
        "_comment": "Generated by notebooks/crosswalks_pipeline.py — do not edit manually.",
        "meta": {
            "title": "Crosswalks of Italy",
            "updated": str(date.today()),
            "source": "OpenStreetMap / ISTAT 2023",
            "unit": "crossings per 10 000 inhabitants",
            "pipeline": "notebooks/crosswalks_pipeline.py",
        },
        "summary": {
            "cities_analyzed": len(cities),
            "total_crosswalks": total_crosswalks,
            "national_average": national_avg,
            "safest_city": cities[0]["name"],
            "least_safe_city": cities[-1]["name"],
        },
        "cities": cities,
    }


# ── Write output ──────────────────────────────────────────────────────
def main():
    print(f"Reading {RAW}")
    rows = load_raw(RAW)
    print(f"  {len(rows)} cities loaded")

    result = process(rows)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"Written → {OUT}")
    print(f"  {result['summary']['cities_analyzed']} cities")
    print(f"  national avg: {result['summary']['national_average']}")
    print(f"  best:  {result['summary']['safest_city']}")
    print(f"  worst: {result['summary']['least_safe_city']}")


if __name__ == "__main__":
    main()
