"""
us_college_greek_pipeline.py
-----------------------------------------------------------------
Data pipeline: US college applicants vs fraternity/sorority rates.

Input:  notebooks/raw/us_college_greek_raw.csv
Output: data/us-college-greek-life.json

Run from project root:
    python notebooks/us_college_greek_pipeline.py
-----------------------------------------------------------------
"""

import csv
import json
import math
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
RAW = ROOT / 'notebooks' / 'raw' / 'us_college_greek_raw.csv'
OUT = ROOT / 'data' / 'us-college-greek-life.json'


def load_raw(path: Path) -> list[dict[str, str]]:
    with open(path, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def pearson(xs: list[float], ys: list[float]) -> float:
    if len(xs) != len(ys) or len(xs) < 2:
        return 0.0

    mean_x = sum(xs) / len(xs)
    mean_y = sum(ys) / len(ys)

    numerator = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    denom_x = math.sqrt(sum((x - mean_x) ** 2 for x in xs))
    denom_y = math.sqrt(sum((y - mean_y) ** 2 for y in ys))

    if denom_x == 0 or denom_y == 0:
        return 0.0

    return round(numerator / (denom_x * denom_y), 2)


def linear_regression(xs: list[float], ys: list[float]) -> tuple[float, float]:
    if len(xs) != len(ys) or len(xs) < 2:
        return (0.0, 0.0)

    mean_x = sum(xs) / len(xs)
    mean_y = sum(ys) / len(ys)

    numerator = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    denominator = sum((x - mean_x) ** 2 for x in xs)

    if denominator == 0:
        return (0.0, round(mean_y, 4))

    slope = numerator / denominator
    intercept = mean_y - slope * mean_x
    return (round(slope, 8), round(intercept, 4))


def median_int(values: list[int]) -> int:
    sorted_vals = sorted(values)
    n = len(sorted_vals)
    mid = n // 2

    if n % 2 == 1:
        return sorted_vals[mid]

    return round((sorted_vals[mid - 1] + sorted_vals[mid]) / 2)


def process(rows: list[dict[str, str]]) -> dict:
    universities: list[dict] = []

    for row in rows:
        universities.append(
            {
                'name': row['university'],
                'region': row['region'],
                'control': row['control'],
                'applicants': int(row['applicants']),
                'admit_rate': float(row['admit_rate']),
                'greek_rate': float(row['greek_rate']),
                'undergrads': int(row['undergrads']),
                'cds_year': int(row['cds_year']),
            }
        )

    # Keep a stable high-to-low view for the scatter narrative.
    universities.sort(key=lambda u: u['applicants'], reverse=True)

    applicants = [u['applicants'] for u in universities]
    greek_rates = [u['greek_rate'] for u in universities]
    admit_rates = [u['admit_rate'] for u in universities]

    applicant_median = median_int(applicants)
    greek_average = round(sum(greek_rates) / len(greek_rates), 1)
    admit_average = round(sum(admit_rates) / len(admit_rates), 1)

    slope, intercept = linear_regression([float(v) for v in applicants], greek_rates)
    corr = pearson([float(v) for v in applicants], greek_rates)

    mega_cutoff = max(80_000, round(applicant_median * 1.35))
    greek_heavy_cutoff = 35.0
    low_greek_cutoff = 15.0

    mega_schools = [u['name'] for u in universities if u['applicants'] >= mega_cutoff]
    mega_low_greek = [
        u['name']
        for u in universities
        if u['applicants'] >= mega_cutoff and u['greek_rate'] <= low_greek_cutoff
    ]
    greek_heavy = [u['name'] for u in universities if u['greek_rate'] >= greek_heavy_cutoff]
    no_greek = [u['name'] for u in universities if u['greek_rate'] == 0]

    top_greek = max(universities, key=lambda u: u['greek_rate'])

    return {
        '_comment': 'Generated by notebooks/us_college_greek_pipeline.py - do not edit manually.',
        'meta': {
            'title': 'Admissions Arms Race, Greek Life Divide',
            'updated': str(date.today()),
            'source': 'Common Data Set 2023-2024 (C1 applicants, F1 fraternity/sorority rates) and institutional reports',
            'unit': 'share of undergraduates in fraternities/sororities (%)',
            'pipeline': 'notebooks/us_college_greek_pipeline.py',
            'caveat': 'Values are institution-level snapshots and can vary by year, campus and reporting definitions.',
        },
        'summary': {
            'universities_analyzed': len(universities),
            'total_applicants': sum(applicants),
            'applicant_median': applicant_median,
            'average_greek_rate': greek_average,
            'average_admit_rate': admit_average,
            'top_greek_school': top_greek['name'],
            'top_greek_rate': top_greek['greek_rate'],
            'no_greek_schools': no_greek,
            'correlation_applicants_greek': corr,
            'mega_applicant_cutoff': mega_cutoff,
            'greek_heavy_cutoff': greek_heavy_cutoff,
            'mega_applicant_schools': mega_schools,
            'mega_low_greek_schools': mega_low_greek,
            'greek_heavy_schools': greek_heavy,
        },
        'regression': {
            'slope': slope,
            'intercept': intercept,
            'x_unit': 'applicants',
            'y_unit': 'greek_rate_percent',
        },
        'universities': universities,
    }


def main() -> None:
    print(f'Reading {RAW}')
    rows = load_raw(RAW)
    print(f'  {len(rows)} rows loaded')

    result = process(rows)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f'Written -> {OUT}')
    print(f"  universities: {result['summary']['universities_analyzed']}")
    print(f"  total applicants: {result['summary']['total_applicants']}")
    print(f"  avg greek rate: {result['summary']['average_greek_rate']}")
    print(
        '  corr(applicants, greek_rate): '
        f"{result['summary']['correlation_applicants_greek']}"
    )


if __name__ == '__main__':
    main()
